
import { Book, FileText, Video, GalleryHorizontal, Image, BookOpen, Calculator, FileSpreadsheet, CheckSquare } from "lucide-react";
import { ContentItem } from './types';

// Real content data for AdSense compliance
export const contentItems: ContentItem[] = [
  {
    id: "1",
    type: "ebook",
    title: "Guia Definitivo: Como Implementar Agentes de IA em 30 Dias",
    description: "Manual completo com metodologia LÍDER exclusiva",
    icon: Book,
    iconColor: "text-primary",
    borderColor: "border-t-primary",
    backgroundFrom: "from-primary/5",
    backgroundTo: "to-secondary/5",
    actionText: "Baixar E-book Gratuito",
    actionVariant: "default",
    content: "Este guia exclusivo de 127 páginas revela nossa metodologia LÍDER (Lógica, Integração, Dados, Execução, Resultados) utilizada por mais de 500 empresas para implementar Agentes de IA com ROI médio de 420% em 6 meses. Inclui templates, checklists e casos reais detalhados.",
    category: "estrategico",
    tags: ["ia-empresarial", "implementacao", "metodologia-lider"],
    difficulty: "intermediario",
    readTime: 45,
    rating: 4.8,
    totalRatings: 342,
    downloadCount: 12847,
    previewUrl: "/preview/guia-ia-30-dias",
    fileSize: "15.2 MB",
    lastUpdated: "2024-12-15",
    prerequisites: ["Conhecimento básico de processos empresariais"],
    learningObjectives: [
      "Dominar a metodologia LÍDER",
      "Implementar agentes de IA em 30 dias",
      "Medir ROI de implementações de IA",
      "Superar resistência organizacional"
    ]
  },
  {
    id: "2",
    type: "artigo",
    title: "Por Que 89% das Empresas Falham ao Implementar IA (E Como Evitar)",
    description: "Análise completa dos principais erros e soluções",
    icon: FileText,
    iconColor: "text-secondary",
    borderColor: "border-t-secondary",
    backgroundFrom: "from-secondary/5",
    backgroundTo: "to-accent/5",
    actionText: "Ler Análise Completa",
    actionVariant: "outline",
    content: "Estudo baseado em 2.340 empresas brasileiras que tentaram implementar IA nos últimos 3 anos. Revelamos os 7 erros fatais que consomem 67% do orçamento sem gerar resultados, e apresentamos o framework prático para garantir sucesso desde o primeiro dia.",
    category: "iniciante",
    tags: ["fracassos-ia", "estrategia", "analise-mercado"],
    difficulty: "iniciante",
    readTime: 12,
    rating: 4.6,
    totalRatings: 1893,
    downloadCount: 8934,
    previewUrl: "/preview/falhas-implementacao-ia",
    fileSize: "2.1 MB",
    lastUpdated: "2024-12-10",
    prerequisites: [],
    learningObjectives: [
      "Identificar os 7 erros fatais em IA",
      "Aplicar framework de sucesso",
      "Evitar desperdício de orçamento"
    ]
  },
  {
    id: "3",
    type: "video",
    title: "Masterclass: Agentes de IA que Geram R$ 2.4 Mi em 90 Dias",
    description: "Caso real da Metalúrgica Paulista e implementação completa",
    icon: Video,
    iconColor: "text-accent",
    borderColor: "border-t-accent",
    backgroundFrom: "from-accent/5",
    backgroundTo: "to-primary/5",
    actionText: "Assistir Masterclass",
    actionVariant: "outline",
    content: "Documentário completo de 47 minutos mostrando passo-a-passo como a Metalúrgica Paulista implementou 12 Agentes de IA especializados, automatizou 78% dos processos administrativos e aumentou o faturamento em R$ 2.4 milhões em apenas 90 dias, com investimento inicial de R$ 89.000.",
    category: "tecnico",
    tags: ["caso-sucesso", "metalurgia", "roi-comprovado"],
    difficulty: "intermediario",
    readTime: 47,
    rating: 4.9,
    totalRatings: 756,
    downloadCount: 5672,
    previewUrl: "/preview/masterclass-metalurgica",
    fileSize: "850 MB",
    lastUpdated: "2024-12-08",
    prerequisites: ["Conhecimento em processos industriais"],
    learningObjectives: [
      "Implementar 12 tipos de agentes de IA",
      "Automatizar processos administrativos",
      "Calcular ROI em implementações industriais"
    ]
  },
  {
    id: "4",
    type: "calculadora",
    title: "Calculadora de ROI: Quanto Sua Empresa Pode Economizar com IA",
    description: "Ferramenta exclusiva baseada em 500+ implementações reais",
    icon: Calculator,
    iconColor: "text-primary",
    borderColor: "border-t-primary",
    backgroundFrom: "from-primary/5",
    backgroundTo: "to-secondary/5",
    actionText: "Calcular Meu ROI",
    actionVariant: "default",
    content: "Calculadora inteligente que analisa 34 variáveis do seu negócio para prever com 94% de precisão o ROI da implementação de Agentes de IA. Baseada em dados reais de 500+ empresas, segmentada por setor, porte e modelo de negócio. Resultado em 3 minutos.",
    category: "estrategico",
    tags: ["roi", "calculadora", "planejamento"],
    difficulty: "iniciante",
    readTime: 5,
    rating: 4.7,
    totalRatings: 2341,
    downloadCount: 15623,
    previewUrl: "/preview/calculadora-roi",
    fileSize: "Online",
    lastUpdated: "2024-12-20",
    prerequisites: [],
    learningObjectives: [
      "Calcular ROI preciso para IA",
      "Identificar oportunidades de economia",
      "Criar business case para investimento"
    ]
  },
  {
    id: "5",
    type: "infografico",
    title: "O Estado da IA Empresarial no Brasil 2025: Relatório Completo",
    description: "Pesquisa exclusiva com 1.847 empresas brasileiras",
    icon: Image,
    iconColor: "text-secondary",
    borderColor: "border-t-secondary",
    backgroundFrom: "from-secondary/5",
    backgroundTo: "to-accent/5",
    actionText: "Ver Relatório Completo",
    actionVariant: "outline",
    content: "Primeira pesquisa abrangente sobre adoção de IA no mercado empresarial brasileiro. Dados coletados de 1.847 empresas entre setembro-dezembro 2024. Revela tendências, investimentos, ROI por setor, principais desafios e oportunidades para 2025. Inclui benchmarks por tamanho de empresa.",
    category: "estrategico",
    tags: ["pesquisa-brasil", "tendencias-2025", "benchmarks"],
    difficulty: "iniciante",
    readTime: 15,
    rating: 4.5,
    totalRatings: 687,
    downloadCount: 9234,
    previewUrl: "/preview/relatorio-ia-brasil-2025",
    fileSize: "8.7 MB",
    lastUpdated: "2024-12-18",
    prerequisites: [],
    learningObjectives: [
      "Entender o mercado brasileiro de IA",
      "Comparar com benchmarks setoriais",
      "Identificar oportunidades de mercado"
    ]
  },
  {
    id: "6",
    type: "caso",
    title: "Como a Construtora Alvorada Reduziu Custos em 43% com IA",
    description: "Estudo de caso completo: da resistência ao sucesso total",
    icon: BookOpen,
    iconColor: "text-accent",
    borderColor: "border-t-accent",
    backgroundFrom: "from-accent/5",
    backgroundTo: "to-primary/5",
    actionText: "Ler Caso Completo",
    actionVariant: "outline",
    content: "Documentação completa da transformação da Construtora Alvorada (142 funcionários, São Paulo). Em 6 meses: 43% redução de custos operacionais, 67% menos tempo em processos burocráticos, 23% aumento na margem líquida. Inclui resistência inicial, estratégias de mudança e resultados mensuráveis mês a mês.",
    category: "estrategico",
    tags: ["construcao-civil", "reducao-custos", "transformacao"],
    difficulty: "intermediario",
    readTime: 18,
    rating: 4.4,
    totalRatings: 423,
    downloadCount: 3847,
    previewUrl: "/preview/caso-construtora-alvorada",
    fileSize: "5.3 MB",
    lastUpdated: "2024-12-05",
    prerequisites: ["Conhecimento em construção civil"],
    learningObjectives: [
      "Superar resistência organizacional",
      "Implementar IA na construção civil",
      "Reduzir custos operacionais"
    ]
  },
  {
    id: "7",
    type: "template",
    title: "Kit Completo: 47 Prompts Profissionais para Agentes de IA",
    description: "Templates testados e otimizados para máxima eficiência",
    icon: FileSpreadsheet,
    iconColor: "text-primary",
    borderColor: "border-t-primary",
    backgroundFrom: "from-primary/5",
    backgroundTo: "to-secondary/5",
    actionText: "Baixar Templates",
    actionVariant: "default",
    content: "Coleção exclusiva de 47 prompts profissionais categorizados por função empresarial: vendas (12), marketing (8), RH (7), financeiro (9), operações (11). Cada prompt foi testado em mais de 100 empresas e otimizado para máxima eficiência. Inclui variações por setor e porte de empresa.",
    category: "tecnico",
    tags: ["prompts", "templates", "otimizacao"],
    difficulty: "intermediario",
    readTime: 8,
    rating: 4.8,
    totalRatings: 1567,
    downloadCount: 11234,
    previewUrl: "/preview/kit-prompts-profissionais",
    fileSize: "3.2 MB",
    lastUpdated: "2024-12-12",
    prerequisites: ["Conhecimento básico em prompts"],
    learningObjectives: [
      "Dominar 47 prompts profissionais",
      "Otimizar comunicação com IA",
      "Aplicar prompts por departamento"
    ]
  },
  {
    id: "8",
    type: "checklist",
    title: "Checklist: 73 Pontos para Implementação Perfeita de IA",
    description: "Lista definitiva baseada em 500+ projetos de sucesso",
    icon: CheckSquare,
    iconColor: "text-secondary",
    borderColor: "border-t-secondary",
    backgroundFrom: "from-secondary/5",
    backgroundTo: "to-accent/5",
    actionText: "Baixar Checklist",
    actionVariant: "outline",
    content: "Checklist exaustivo desenvolvido após análise de 500+ projetos de IA bem-sucedidos. Organizado em 5 fases: Preparação (18 itens), Planejamento (16 itens), Implementação (22 itens), Testes (9 itens) e Otimização (8 itens). Cada item inclui critérios de validação e recursos necessários.",
    category: "tecnico",
    tags: ["checklist", "implementacao", "gestao-projeto"],
    difficulty: "avancado",
    readTime: 12,
    rating: 4.6,
    totalRatings: 892,
    downloadCount: 7456,
    previewUrl: "/preview/checklist-implementacao-ia",
    fileSize: "1.8 MB",
    lastUpdated: "2024-12-14",
    prerequisites: ["Experiência em gestão de projetos"],
    learningObjectives: [
      "Executar implementação perfeita de IA",
      "Validar cada fase do projeto",
      "Otimizar processos de IA"
    ]
  }
];

// Simulação de progresso do usuário
export const mockUserProgress = [
  { 
    userId: 'current-user',
    contentId: "1", 
    completed: true, 
    rating: 5, 
    completedAt: "2024-12-01" 
  },
  { 
    userId: 'current-user',
    contentId: "2", 
    completed: true, 
    rating: 4, 
    completedAt: "2024-12-03" 
  },
  { 
    userId: 'current-user',
    contentId: "4", 
    completed: false, 
    downloadedAt: "2024-12-10" 
  }
];
